### ISSUE TITLE
N3C OMOP -> OWL/FHIR

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#104]
## Overview
Convert some N3C OMOP concept tables to OWL and FHIR.

## Sub-task list
- [x] 1. Convert to OWL
- [x] 2. Convert to FHIR (a. static JSON, or b. NPM package)
- [x] 3. Load or automate ingest?

### 1. Convert to OWL
This sub-task is a mirror of the work being done in the `n3c-owl-ingest` repository, where N3C's OMOP tables (`concept`, `concept_relationship`) are being converted to OWL ([pull request](https://github.com/HOT-Ecosystem/n3c-owl-ingest/pull/1)).

## Related
- https://github.com/HOT-Ecosystem/n3c-owl-ingest/issues/12
- https://github.com/HOT-Ecosystem/hapi-issues/issues/59

**Comment by joeflack4** [comment]
@DaveraGabriel @ShahimEssaid @Leskena2 @putmantime @Sigfried Just wanted to update on conformity with the recent decisions made with representing OMOP, e.g. "[Approach three: OMOP Code System with ConceptMaps](https://github.com/HL7/fhir/wiki/OMOP-terminology-discussion#possible-approach-three-omop-code-system-with-conceptmaps)".

This looks really simple. We have the OWL part done. For OMOP on FHIR, I think I just need to make a modification to OAK we've wanted for a while: **OWL -> (CodeSystem + ConceptMaps)**; we're missing the ConceptMap part. Right now, relationships / mappings exist within the CodeSystem under `concept.property`. We should add an option (maybe even default) to moving all of these relationships to ConceptMap instead.

**Comment by joeflack4** [comment]
Though improvements still to be made, the bulk has been achieved by:
- https://github.com/HOT-Ecosystem/n3c-ingest/pull/2
