### ISSUE TITLE
OMOP2FHIR for OHDSI Symposium Oct2023

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#107]
## Overview
By the Oct20-22 OHDSI symposium, should have completed OMOP2FHIR package.

Each component in "sub tasks" should have its own repository and release on PyPi.

I've checked off "optional" ones for now even though they haven't been done, just to give a better idea of critical progress. Still considering doing them though.

## Sub-tasks
- [x] 1. New OMOP2FHIR dependencies: Split up & connect various repos
  - [x] 1.1. **N3C OWL Ingest**: extract OMOP2FHIR separately (#104)
  - [x] 1.2. **OMOP2FHIR**: refactor out of "N3C OWL Ingest" (https://github.com/HOT-Ecosystem/n3c-owl-ingest/issues/12)
  - [x] 1.3. **OMOP2OWL** (optional): refactor out of "N3C OWL Ingest"
- [x] 2. Existing OMOP2FHIR dependencies: updates
  - [x] 2.1. **OWL2FHIR**: Should produce ConceptMaps, not just CodeSystems
  - [ ] 2.2. **SSSOM**: includes #85 (will do this one later)
  - [x] 2.3. **OAK (optional)**: Run ConceptMaps from within OAK rather than after OAK step

## Additional details
[OMOP2FHIR & N3C Ingest: dependency and IO diagrams](https://docs.google.com/presentation/d/1vz6Df7f8psID8OBolXHhSw6Fq-Mi0TjdNTHF-zSmbwg/edit#slide=id.p)
<details><summary>Screenshot</summary>
<p>

<img width="1240" alt="Screen Shot 2023-09-17 at 5 22 21 PM" src="https://github.com/HOT-Ecosystem/hapi-issues/assets/13045020/009db439-502f-4d65-aed9-82ca995f6988">

</p>
</details>

**Comment by joeflack4** [comment]
Though future improvements remain, the minimum viable work for this is complete.
