### ISSUE TITLE
DNS: Stable URL / domain setup (Website & HAPI server)

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#119]
## Sub-task list
- [x] 1. Purchase domain
- [x] 2. Route to [GH pages site](https://hot-ecosystem.github.io/tims-website/)
- [x] 3. Route to HAPI server as subdomain? http://20.3.198.176:8080/ or http://20.3.198.176:8080/fhir/swagger-ui/
- [x] 4. Update the page referenced in #141

#### Domain name ideas
Either .org, .com, or .edu
Most of the group seems to like 'tims' to be in the domain, or something about med / biomed.

See more: [Google Sheet](https://docs.google.com/spreadsheets/d/1V68ap3xhHlnrmDobmi6rUxxBr9QxXOJcHLNK7AnRbJk/edit#gid=876912119)

<details><summary>Details</summary>
<p>

Generally about terminology:
- terminfra
- term-infra
- terminologyinfrastructure
- terminology-infrastructure
- termservices
- term-services
- terminologyservices
- terminology-services (Joe & Melissa like)
- termcentral
- term-central
- terminologycentral
- terminology-central (Joe & Melissa like)
- termz
- termforge
- term-forge
- terminologyforge
- terminology-forge
- termnexus
- term-nexus
- terminologynexus
- terminology-nexus

Has medical / biomedical in it:
- biomedterminology
- biomed-terminology
- biomedicalterminology
- biomedical-terminology
- biomedicalterminologyservices
- biomedical-terminology-services
- biomedicalterminologynexus
- biomedical-terminology-nexus
- biomedterminologyhub
- biomed-terminology-hub
- biomedicalterminologyhub
- biomedical-terminology-hub

Has 'tims' in it:
- timsts
- teamtims
- team-tims
- timsgroup
- tims-group
- timsterminology
- tims-terminology
- timsservices
- tims-services
- ~tims (.org and .com are taken, and we can't really do .edu)~

Has 'tims' and medical / biomedical in it:
- medtims
- med-tims
- timsmed
- tims-med
- timsbiomed
- tims-biomed
- timsbiomedical
- tims-biomedical

</p>
</details> 

## Related
- #40
- #125

**Comment by Leskena2** [comment]
tims.edu (I know tims.org and tims.com are taken)
medtims.org, medtims.com, med_tims.org, med_tims.com

**Comment by joeflack4** [comment]
FYI with [Namecheap's "beast mode"](https://www.namecheap.com/domains/registration/results/?domain=&type=beast), you can check the availability of multiple domains at once.

I sent out an email to the team asking for votes.

**Comment by joeflack4** [comment]
## Supporting R4 and R5
Ideally these go to different addresses. They may be different ports at the same IP, or different IPs.

I'm thinking something like this:
1. http://fhir.DOMAIN.org  --> http://20.3.198.176:8080/fhir/
2. http://fhir-r4.DOMAIN.org --> http://20.3.198.176:8080/fhir/
3. http://fhirr4.DOMAIN.org --> http://20.3.198.176:8080/fhir/
4. http://r4.DOMAIN.org --> http://20.3.198.176:8080/
5. http://fhir.DOMAIN.org/r4 --> http://20.3.198.176:8080/fhir/
6. http://fhir.DOMAIN.org/r5 --> URL_TBD
7. http://fhir-r5.DOMAIN.org --> URL_TBD
8. http://fhirr5.DOMAIN.org --> URL_TBD
9. http://r5.DOMAIN.org --> URL_TBD

If this can't be configured properly in Azure, we could do a reverse proxy.


<details><summary>Additional notes</summary>
<p>

http://20.3.198.176:8080/ -> Goes to R4 HAPI UI
http://20.3.198.176:8080/fhir -> R4 endpoint. In browser it reroutes to http://20.3.198.176:8080/fhir/swagger-ui/
http://20.3.198.176:8080/fhir/swagger-ui/ -> R4 Swagger UI

</p>
</details>

**Comment by joeflack4** [comment]
I think that when the rerouting to https://hot-ecosystem.github.io/tims-website/ or http://20.3.198.176:8080/fhir/ happens, that will be the URL that will show in the address bar.  But rerouting to http://20.3.198.176:8080/ will not change the address? If so, should ideally set things up differently so the domain doesn't change.
