### ISSUE TITLE
Transfer server to TISLab

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#159]
## Overview
We want to move ownership of the FHIR server from JHU Azure, managed under BIDS, to TISLab.

## Sub-tasks
'Other' would be someone from Melissa's team responsible for dealing with this server infrastructure, possibly Shahim.

- [ ] Melissa's team: Decide if they want to / can host this on Azure
- [x] @joeflack4 Email cloudrequests@jhmi.edu and figure out what to do.
- [ ] @joeflack4 Relay the information to other.
- [ ] @joeflack4 &/or other: Handle the transfer

### Resources
- [VM](https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/f2d8956b-a09b-4f8d-a76a-899b805993ae/resourceGroups/HAPI-N3C-Ubuntu-22.04_group/providers/Microsoft.Compute/virtualMachines/HAPI-N3C-Ubuntu-22.04/overview)
- [Resource Group](https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/f2d8956b-a09b-4f8d-a76a-899b805993ae/resourceGroups/HAPI-N3C-Ubuntu-22.04_group/overview)
- [Subscription](https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/f2d8956b-a09b-4f8d-a76a-899b805993ae/overview) (also includes other non-TIMS related stuff)

### Conversations
<details><summary>Convo w/ JH infra team</summary>
<p>

Joe: 
> How to change subscription owner?
> Basically my boss collaborates on this grant with someone from another university. I think that we are going to hand off this VM, and probably the full subscription, to that other team

Martin:
> For the subscription owner change, you should probably email cloudrequests@jhmi.edu who should be able to help. 

</p>
</details>

**Comment by joeflack4** [comment]
This is done. We've backed up the important parts of the server in both of these locations:

- [onedrive](https://livejohnshopkins-my.sharepoint.com/personal/jflack1_jh_edu/_layouts/15/filebrowser.aspx?id=%2Fsites%2FBiomedicalInformaticsandDataScience%2FShared%20Documents%2FResearch%2FProjects%2FTIMS%2FServer%20backup&listurl=https%3A%2F%2Flivejohnshopkins%2Esharepoint%2Ecom%2Fsites%2FBiomedicalInformaticsandDataScience%2FShared%20Documents&viewid=51daccc9%2D8479%2D4ef4%2Da7bf%2D65b689881f3a&p=31)
- [gdrive](https://drive.google.com/drive/u/0/folders/1er1engPRTQIwZXeeR96HFHHMcGGx4dra)
