### ISSUE TITLE
DNS & SSL

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#78]
## Sub-tasks
- [ ] 1. Choose a domain / domain name
- [ ] 2. Connect server to domain / subdomain
- [ ] 3. Set up SSL #125

### 1. Choose a domain / domain name
a. Use: http://fhir.hotecosystem.org/ ?

### 2. Connect server to domain / subdomain
If (a) http://fhir.hotecosystem.org/, Joe may have all of the access / information needed to do this. Looks like web host is AWS. Should be able to add _A record_ linking to our IP there. Otherwise may need to finagle w/ Nginx. Requires JHU VPN to SSH into the linux box.

### 3. Set up SSL
Once we set this up on a subdomain, _may_ be able to use [LetsEncrypt](https://help.skysilk.com/support/solutions/articles/9000139836-how-to-install-let-s-encrypt-on-ubuntu-linux-vps-to-create-ssl-certificates) to do this easily. Not sure if this needs to be done on the proxy server (where hotecosystem.org is being hosted currently), or the web server (where our HAPI service is).

**Comment by chrisroederucdenver** [comment]
hot-ecosystem.org, hot-ecosystem.net ?

SSL is the pressing issue because the way TSDemoBoard is hosted on github with https, it trips browser security when hitting services on http. A workaround is to modify settings.

from Joe, [a web post on doing SSL](https://serverspace.us/support/help/how-to-get-lets-encrypt-ssl-on-ubuntu/)

**Comment by joeflack4** [comment]
Closing as now redundant with #119 and #125
