### ISSUE TITLE
ValueSets: VSAC

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#91]
## Overview
VSAC may have a bounty of ValueSets for us to extract.

## Questions
- [ ] 1. Are ValueSets (mostly) intensional or extensional?
- [ ] 2. Which data sources to use?
a. Pre-made packages: http://fhir.org/packages/us.nlm.vsac/
How often are these updated?
b. VSAC FHIR API: https://www.nlm.nih.gov/vsac/support/usingvsac/vsacfhirapi.html

## Sub-tasks
- [ ] 1. Can extract all extensional ValueSets as-is
- [ ] 2. For intensional, need to import only when have requisite vocab(s) (and version?)
- [ ] 3. Set up automated schedule for downloading new and updated ValueSets

**Comment by joeflack4** [comment]
@ShahimEssaid @Sigfried I didn't see an existing issue for this so I created; feel free to update/add.
